version: '3.8'

services:
  db:
    image: postgres:16
    container_name: shiftease-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shift_ease
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shift_ease"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:3007
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=shift_ease;Username=postgres;Password=admin
    ports:
      - "3007:3007"
    expose:
      - "3007"
    depends_on:
      db:
        condition: service_healthy
        

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3006:80"
    expose:
      - "3006"
    depends_on:
      - backend

  proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    

volumes:
  postgres_data:
