version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shiftease-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:3007
      - ConnectionStrings__DefaultConnection=Host=shared-postgres;Port=5432;Database=shift_ease;Username=postgres;Password=PGtitan4321
    expose:
      - "3007"
    networks:
      - proxy_net
      - db_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shiftease-frontend
    expose:
      - "80"
    networks:
      - proxy_net
    depends_on:
      - backend

networks:
  proxy_net:
    external: true
  db_net:
    external: true
