START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215155737_ConsolidatedMigration') THEN
    ALTER TABLE "Vacations" DROP CONSTRAINT "FK_Vacations_Employees_EmployeeId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215155737_ConsolidatedMigration') THEN
    DROP TABLE "DayOffPreferences";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215155737_ConsolidatedMigration') THEN
    DROP INDEX "IX_Vacations_EmployeeId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215155737_ConsolidatedMigration') THEN
    ALTER TABLE "SickLeaves" DROP COLUMN "Accepted";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215155737_ConsolidatedMigration') THEN
    ALTER TABLE "SickLeaves" DROP COLUMN "Rejected";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215155737_ConsolidatedMigration') THEN
    CREATE TYPE schedule_pattern AS ENUM ('custom', 'two_on_two_off', 'five_on_two_off', 'three_on_three_off', 'four_on_four_off');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215155737_ConsolidatedMigration') THEN
    ALTER TABLE "Vacations" ALTER COLUMN "StartDate" TYPE date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215155737_ConsolidatedMigration') THEN
    ALTER TABLE "Vacations" ALTER COLUMN "EndDate" TYPE date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215155737_ConsolidatedMigration') THEN
    CREATE TABLE "PersonalDayRequests" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EmployeeId" integer NOT NULL,
        "StartDate" date NOT NULL,
        "EndDate" date NOT NULL,
        "Accepted" boolean NOT NULL,
        "Rejected" boolean NOT NULL,
        CONSTRAINT "PK_PersonalDayRequests" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215155737_ConsolidatedMigration') THEN
    CREATE TABLE "PersonalDays" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EmployeeId" integer NOT NULL,
        "StartDate" date NOT NULL,
        "EndDate" date NOT NULL,
        CONSTRAINT "PK_PersonalDays" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215155737_ConsolidatedMigration') THEN
    CREATE TABLE "SickLeaveRequests" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EmployeeId" integer NOT NULL,
        "StartDate" date NOT NULL,
        "EndDate" date NOT NULL,
        "Accepted" boolean NOT NULL,
        "Rejected" boolean NOT NULL,
        CONSTRAINT "PK_SickLeaveRequests" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215155737_ConsolidatedMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251215155737_ConsolidatedMigration', '9.0.7');
    END IF;
END $EF$;
COMMIT;

