START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251215155737_ConsolidatedMigration') THEN
        IF EXISTS (
            SELECT 1 FROM information_schema.table_constraints
            WHERE constraint_name = 'FK_Vacations_Employees_EmployeeId'
            AND table_name = 'Vacations'
        ) THEN
            ALTER TABLE "Vacations" DROP CONSTRAINT "FK_Vacations_Employees_EmployeeId";
        END IF;

        DROP TABLE IF EXISTS "DayOffPreferences";

        DROP INDEX IF EXISTS "IX_Vacations_EmployeeId";

        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'SickLeaves' AND column_name = 'Accepted'
        ) THEN
            ALTER TABLE "SickLeaves" DROP COLUMN "Accepted";
        END IF;

        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'SickLeaves' AND column_name = 'Rejected'
        ) THEN
            ALTER TABLE "SickLeaves" DROP COLUMN "Rejected";
        END IF;

        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'schedule_pattern') THEN
                CREATE TYPE schedule_pattern AS ENUM ('custom', 'two_on_two_off', 'five_on_two_off', 'three_on_three_off', 'four_on_four_off');
            END IF;
        END $$;

        ALTER TABLE "Vacations" ALTER COLUMN "StartDate" TYPE date;
        ALTER TABLE "Vacations" ALTER COLUMN "EndDate" TYPE date;

        CREATE TABLE IF NOT EXISTS "PersonalDayRequests" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "EmployeeId" integer NOT NULL,
            "StartDate" date NOT NULL,
            "EndDate" date NOT NULL,
            "Accepted" boolean NOT NULL,
            "Rejected" boolean NOT NULL,
            CONSTRAINT "PK_PersonalDayRequests" PRIMARY KEY ("Id")
        );

        CREATE TABLE IF NOT EXISTS "PersonalDays" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "EmployeeId" integer NOT NULL,
            "StartDate" date NOT NULL,
            "EndDate" date NOT NULL,
            CONSTRAINT "PK_PersonalDays" PRIMARY KEY ("Id")
        );

        CREATE TABLE IF NOT EXISTS "SickLeaveRequests" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY,
            "EmployeeId" integer NOT NULL,
            "StartDate" date NOT NULL,
            "EndDate" date NOT NULL,
            "Accepted" boolean NOT NULL,
            "Rejected" boolean NOT NULL,
            CONSTRAINT "PK_SickLeaveRequests" PRIMARY KEY ("Id")
        );

        INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
        VALUES ('20251215155737_ConsolidatedMigration', '9.0.7');
    END IF;
END $EF$;

COMMIT;
